# Generated by Django 3.2.9 on 2022-06-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True, verbose_name='股票简称')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='股票代码')),
                ('area', models.CharField(max_length=8, verbose_name='地域')),
                ('industry', models.CharField(max_length=8, verbose_name='所属行业')),
                ('market', models.CharField(max_length=8, verbose_name='市场类型')),
            ],
            options={
                'verbose_name': '股票信息',
                'verbose_name_plural': '股票信息',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('name', models.CharField(max_length=10, verbose_name='股票简称')),
                ('industry', models.CharField(max_length=8, verbose_name='所属行业')),
                ('tm', models.CharField(max_length=10, verbose_name='数字时间')),
                ('time', models.TimeField(max_length=10, verbose_name='时间')),
                ('type', models.CharField(choices=[('666', '六六大顺'), ('8201', '火箭发射'), ('8202', '快速反弹'), ('8193', '大笔买入'), ('4', '封涨停板'), ('32', '打开跌停板'), ('64', '有大买盘'), ('8207', '竞价上涨'), ('8209', '高开5日线'), ('8211', '向上缺口'), ('8213', '60日新高'), ('8215', '60日大幅上涨'), ('8204', '加速下跌'), ('8203', '高台跳水'), ('8194', '大笔卖出'), ('8', '封跌停板'), ('16', '打开涨停板'), ('128', '有大卖盘'), ('8208', '竞价下跌'), ('8210', '低开5日线'), ('8212', '向下缺口'), ('8214', '60日新低'), ('8216', '60日大幅下跌')], max_length=10, verbose_name='类型')),
                ('info', models.FloatField(verbose_name='原始数据')),
                ('pct_chg', models.FloatField(verbose_name='幅度')),
                ('hand', models.FloatField(verbose_name='手数')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('market', models.FloatField(verbose_name='流通市值')),
            ],
            options={
                'verbose_name': '盘口异动',
                'verbose_name_plural': '盘口异动',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockChangeFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('name', models.CharField(max_length=10, verbose_name='股票简称')),
                ('industry', models.CharField(max_length=8, verbose_name='所属行业')),
                ('time', models.CharField(max_length=10, verbose_name='时间')),
                ('type', models.CharField(choices=[('666', '六六大顺'), ('8201', '火箭发射'), ('8202', '快速反弹'), ('8193', '大笔买入'), ('4', '封涨停板'), ('32', '打开跌停板'), ('64', '有大买盘'), ('8207', '竞价上涨'), ('8209', '高开5日线'), ('8211', '向上缺口'), ('8213', '60日新高'), ('8215', '60日大幅上涨'), ('8204', '加速下跌'), ('8203', '高台跳水'), ('8194', '大笔卖出'), ('8', '封跌停板'), ('16', '打开涨停板'), ('128', '有大卖盘'), ('8208', '竞价下跌'), ('8210', '低开5日线'), ('8212', '向下缺口'), ('8214', '60日新低'), ('8216', '60日大幅下跌')], max_length=10, verbose_name='类型')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('pct_chg', models.FloatField(verbose_name='幅度')),
                ('market', models.FloatField(verbose_name='流通市值')),
                ('tm', models.CharField(max_length=8, verbose_name='时间区分')),
                ('c', models.SmallIntegerField(verbose_name='指数')),
            ],
            options={
                'verbose_name': '盘口异动',
                'verbose_name_plural': '盘口异动',
                'ordering': ['c'],
            },
        ),
        migrations.CreateModel(
            name='StockDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True)),
                ('code', models.CharField(max_length=10, verbose_name='股票代码')),
                ('name', models.CharField(max_length=10, verbose_name='股票简称')),
                ('industry', models.CharField(max_length=8, verbose_name='所属行业')),
                ('open', models.FloatField(verbose_name='开盘价')),
                ('close', models.FloatField(verbose_name='收盘价')),
                ('low', models.FloatField(verbose_name='最高价')),
                ('high', models.FloatField(verbose_name='最低价')),
                ('pct_chg', models.FloatField(verbose_name='涨跌幅')),
                ('return_0', models.FloatField(verbose_name='实际涨跌幅')),
                ('pre_close', models.FloatField(verbose_name='昨天收盘价')),
                ('volume', models.FloatField(verbose_name='成交量')),
                ('amount', models.FloatField(verbose_name='成交额')),
                ('turn', models.FloatField(verbose_name='换手率')),
                ('market', models.FloatField(verbose_name='流通市值')),
            ],
            options={
                'verbose_name': '当日行情',
                'verbose_name_plural': '当日行情',
                'ordering': ['id'],
            },
        ),
    ]
